-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 10:53:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `ticker` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NULL,
  `exchange` VARCHAR(50) NULL,
  PRIMARY KEY (`ticker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`score_cache` (
  `ticker` VARCHAR(10) NOT NULL,
  `pe_ratio` DECIMAL(10,2) NULL,
  `debt_to_equity` DECIMAL(10,2) NULL,
  `revenue_growth` DECIMAL(10,2) NULL,
  `profit_margin` DECIMAL(10,2) NULL,
  `stock_price` DECIMAL(12,4) NULL,
  `data_updated_at` DATETIME NULL,
  `score_updated_at` DATETIME NULL,
  `company_ticker` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ticker`),
  INDEX `fk_score_cache_company1_idx` (`company_ticker` ASC) VISIBLE,
  CONSTRAINT `fk_score_cache_company1`
    FOREIGN KEY (`company_ticker`)
    REFERENCES `mydb`.`company` (`ticker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`score_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calculated_date` DATETIME NULL,
  `fundamental_score` DECIMAL(5,2) NULL,
  `valuation_score` DECIMAL(5,2) NULL,
  `debt_score` DECIMAL(5,2) NULL,
  `growth_score` DECIMAL(5,2) NULL,
  `margin_score` DECIMAL(5,2) NULL,
  `stock_price` DECIMAL(12,4) NULL,
  `company_ticker` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_score_history_company1_idx` (`company_ticker` ASC) VISIBLE,
  CONSTRAINT `fk_score_history_company1`
    FOREIGN KEY (`company_ticker`)
    REFERENCES `mydb`.`company` (`ticker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
